import { useDemo, useState } from 'react'
import { GoogleMap, useJsApiLoader, Marker } from "@react-google-maps/api"
import Head from "next/head";
import SideNavBar from './../component/SideNavbar'


function usersMapLocations() {

  const [location, setLocation] = useState('Maps Locations');

  function Map() {
    const position = { lat: 39.925533, lng: 32.866287 };
    return (
      <GoogleMap zoom={6} center={{ lat: 39.925533, lng: 32.866287 }}  mapContainerClassName="map-container" onClick={(e) => {setLocation(e.zb)}}  >
      <Marker position={{ lat: 39.925533, lng: 32.866287 }}  icon={{
        // path: google.maps.SymbolPath.CIRCLE,
        url: "../../../styles/ico/map.png",
        scaledSize: { width: "30px", height: "30px" },
        anchor: { x: 15, y: 15 },
      }}   />
      </GoogleMap>

    );
  }
  const { isLoaded } = useJsApiLoader({
    googleMapsApiKey: "AIzaSyAhkyqtF5czuz-KzzOv3Z8skkl2b_9koDk",

  });

  if (!isLoaded) return <div>Loading....!</div>
  return (
    <>
      <Head>
        <title>Test Case - Users Map Locations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <div className="md:flex min-h-screen relative">
        <SideNavBar />
        <div className="md:flex w-full p-10 min-h-screen flex-col justify-start">
          <h1 className="text-xl font-bold">User Map Locations</h1>
          <div className='md:flex w-full flex-row justify-start items-start mb-1 '>


            <form action="#" method="POST" className=' mt-6 md:flex w-full flex-row justify-start items-start '>

              <div className='w-1/5'>
                <label className="block text-gray-700 w-1/5">Username</label>
                <select onChange={(e) => console.log(e.target.value)} className="w-full  px-4 py-3 rounded-lg bg-gray-200 mt-2 border focus:border-blue-500 focus:bg-white focus:outline-none">
                  <option value="a">a</option>
                  <option selected value="b">b</option>
                  <option value="c">c</option>
                  <option value="d">d</option>
                </select>
              </div>
              <div className='w-2/5 ml-1'>
                <label className="block text-gray-700 w-full">Locations</label>
                <input
                  type="text"
                  name=""
                  id=""
                  placeholder={location}
                  className="w-full px-4 py-3 rounded-lg bg-gray-200 mt-2 border focus:border-blue-500 focus:bg-white focus:outline-none"
                  autofocus=""
                  autoComplete=""
                  required=""
                />
              </div>
              <div className='w-0.5/5 ml-1'>

                <button
                  type="submit"
                  className="w-full block  bg-blue-500 hover:bg-blue-400 focus:bg-blue-400 text-white font-semibold rounded-lg
          px-4 py-3 mt-8"
                >
                  Locations Edit
                </button>
              </div>


            </form>


          </div>
          <div className='w-full h-full'>
            <Map />

          </div>









        </div>
      </div>
    </>
  )
}

export default usersMapLocations

