import React, { useEffect, useState } from 'react'
import axios from './../../apiConfig/axios'
import Head from "next/head";
import SideNavBar from './../component/SideNavbar'
function users() {
  const [userList,setUserList]=useState([])

 

  useEffect(() => {


    axios.get(`userList.php`).then(response => {
      setUserList(response.data.usersList);

     



    });

  })


   
  return (
    <>
      <Head>
        <title>Test Case - Users</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <div className="md:flex min-h-screen relative bg-neutral-100">
        <SideNavBar />
        <div className="w-full p-10 flex justify-center  flex-col">

          <div className='mb-10 mt-30'>
             <h3 className='text-black font-bold'>User List</h3>
          </div>



          <div className='  flex justify-start items-start h-screen'>
          <table className='shadow-2x1 font-[Poppins] border-2 border-black w-6/12'>
            <thead className='text-black border-2 border-black'>
              <tr>
                <th>Name</th>
                <th>Surname</th>
                <th>Username</th>
                <th>Locaitons</th>
              </tr>
            </thead>
            <tbody className='text-cyan-900 text-left'>
            {userList.map(function(e,key){
                return(

<tr className='bg-neutral-200 cursor-pointer duration-300 '>
                <td className='py-3 px-6 '>
                 {e.Name}
                </td>
                <td className='py-3 px-6'>
                {e.Surname}
                </td>
                <td className='py-3 px-6'>
                {e.Username}
                </td>
                <td className='py-3 px-6'>
                {e.Locations}
                </td>
              </tr>



                )



            })}

              


            </tbody>
          </table>
          </div>
         
        </div>
      </div>
    </>
  )
}

export default users