import { useDemo, useState, useEffect } from 'react'
import GoogleMapReact from 'google-map-react';
import Head from "next/head";
import SideNavBar from './../component/SideNavbar'
import axios from '../../apiConfig/axios';

import swal from 'sweetalert';




export default function usersMapLocations() {
  const initialState = [
    {id: 1, lat:10,lng:10},
   
  ];
  const [location, setLocation] = useState(initialState)
  const [name, setName] = useState()
  const [surname, setSurname] = useState()
  const [username, setUsername] = useState()
 const[saveButton,setSaveButton]=useState(false)



  const [latLng, setLatLng] = useState();
  const [maps, setMaps] = useState(null);
  const [map, setMap] = useState(null);

  
  const [userList, setUserList] = useState()
  const [selectedUser, setSelectedUser] = useState()

  useEffect(() => {


    setSelectedUser(window.sessionStorage.getItem("Registeruser"));

    console.log(selectedUser)
    if (selectedUser !== "") {


      axios.post(`userData.php`, { selectedUser }).then(response => {
        setUsername("sa")
        setSurname(response.data.Surname)
        setName(response.data.Name)


      })
    }
    else {
      setSelectUser("Select User")
    }

    axios.get(`userList.php`).then(response => {
      setUserList(response.data.usersList);

    });

  },[])


  const MapMarker = ({ position, maps, map }) => {

    useEffect(() => {

      const marker = new maps.Marker({
        position,
        map,
        title: "Hello World!",
      });
      console.log(location)
     
    }, [position?.lat, position?.lng])
    return (
      <></>
    )

  }

  const handleApiLoaded = (map, maps) => {
    setMap(map);
    setMaps(maps);
    map.setOptions({

      fullscreenControl: false,
      mapTypeControl: true,
      mapTypeControlOptions: {


        style: maps.MapTypeControlStyle.DEFAULT,
        position: maps.ControlPosition.TOP_CENTER,
        mapTypeIds: ["roadmap", "satellite"],
      },
      zoomControl: false,
    });
  };

  const defaultProps = {
    center: {
      lat: 41.013281483623146,
      lng: 28.978454052998472
    },
    zoom: 6
  };

  function Locationset (e){
  
      setLocation(current => [...current, {id: location.length , lat:e.lat,lng:e.lng}]);
      setSaveButton(true)

  }
  function saveUserLocations (e){

      
      swal({
        title: "Are you sure?",
        text: "Do you want to save the locations selected for the user?",
        icon: "info",
        buttons: true,
        dangerMode: true,
      })
      .then((adduser) => {
        if (adduser) {
          axios.post(`locationsAdd.php`,{e,username}).then(response => {
      
            console.log(response.data.userData)
            if(response.data.message){
              
              swal("Successfully registered.", {
                icon: "success",
              })
             
            }
            else{
              console.log("error! try again.")
            }
            
          
           
          });
          
        } else {
          swal("You have canceled adding users.");
        }
      });

}

  function userSelectedChange (e){
    console.log(e)
    axios.post(`userData.php`, {e}).then(response => {
      setUsername(response.data.username)
      setSurname(response.data.surname)
      setName(response.data.name)
      setSelectedUser(response.data.username)

    })
  }



  return (
    <>
      <Head>
        <title>Test Case - Users Map Locations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <div className="md:flex min-h-screen relative">
        <SideNavBar />
        <div className="md:flex w-full p-10 min-h-screen flex-col justify-start">
          <h1 className="text-xl font-bold">User Map Locations</h1>
          <div className='md:flex w-full flex-col justify-start items-start mb-1 '>
            <form action="#" method="POST" className=' mt-6 md:flex w-full flex-row justify-start items-start '>

              <div className='w-1/5'>
                <label className="block text-gray-700 w-1/5">Username</label>
                <select onChange={(e) =>{ setSelectedUser(e.target.value), userSelectedChange(e.target.value)}} className="w-full  px-4 py-3 rounded-lg bg-gray-200 mt-2 border focus:border-blue-500 focus:bg-white focus:outline-none">
                {userList?.map(function(e,key){
                  return(
                    <option value={e.Username}>{e.Username}</option>
                  )
                })}
                </select>
              </div>



                  {console.log(location)}

            </form>

            <div className=' p-10 flex flex-col'>
              <label>Name:  {name}  </label>
              <label>  Surname: {surname}  </label>
              <label>   Username: {username}</label>

            </div>



          </div>
          <div className='w-full h-full mapcontainer'>
            <GoogleMapReact
              bootstrapURLKeys={{ key: "AIzaSyAhkyqtF5czuz-KzzOv3Z8skkl2b_9koDk" }}
              defaultCenter={defaultProps.center}
              defaultZoom={defaultProps.zoom}
              onClick={(e) => { setLatLng(e),Locationset(e),console.log(e) }}
              
              onGoogleApiLoaded={({ map, maps }) => {
                handleApiLoaded(map, maps);
              }}

            >
              {!!latLng ?
                <>
                  <MapMarker map={map} maps={maps} position={latLng}></MapMarker>
                </> : <></>

              }
            </GoogleMapReact>
            <div style={{display: saveButton ? "block" : "none"}} className="w-full">
            <button
              onClick={(e) => saveUserLocations(location)}
                          type="submit"
                          className="w-2/5 block  bg-green-500 hover:bg-blue-400 focus:bg-blue-400 text-white font-semibold rounded-lg
          px-4 py-3 mt-2" 
                        >
                         Save Location
                        </button>
              </div>
         
          </div>









        </div>
      </div>
    </>
  )
}



