import React from 'react'

import Head from "next/head";
import SideNavBar from './../component/SideNavbar'
function userAdd() {
  return (
    <>
    <Head>
      <title>Test Case - User Add</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/pro.ico" />
    </Head>
    <div className="md:flex min-h-screen relative">
      <SideNavBar />
      <div className="w-full p-10">
        In aliquip non incididunt aliqua magna ea enim amet. Nisi id aliqua eu officia eiusmod aute tempor aliquip et cupidatat aute nisi ex. Nisi velit eiusmod irure ullamco sint enim anim pariatur sunt commodo est ad. Eu labore enim duis cupidatat irure est culpa laborum proident eu ea elit. Do ut in nostrud esse eu nulla consectetur.
      </div>
    </div>

  
  </>
  )
}

export default userAdd