import React from 'react'

import Head from "next/head";
import SideNavBar from './../component/SideNavbar'
function users() {
  return (
    <div className="bg-blue-800">
    <Head>
      <title>Test Case - Users</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/pro.ico" />
    </Head>
    <SideNavBar />
  </div>
  )
}

export default users