import { useDemo, useState } from 'react'
import { GoogleMap, useJsApiLoader, Marker } from "@react-google-maps/api"

import Head from "next/head";
import SideNavBar from './../component/SideNavbar'
function userAdd() {

  const [location, setLocation] = useState('Maps Locations');

  function Map() {
    const position = { lat: 39.925533, lng: 32.866287 };
    return (
      <GoogleMap zoom={6} center={{ lat: 39.925533, lng: 32.866287 }}  mapContainerClassName="map-container" onClick={(e) => {setLocation(e.zb)}}  >
      <Marker position={{ lat: 39.925533, lng: 32.866287 }}  icon={{
        // path: google.maps.SymbolPath.CIRCLE,
        url: "../../../styles/ico/map.png",
        scaledSize: { width: "30px", height: "30px" },
        anchor: { x: 15, y: 15 },
      }}   />
      </GoogleMap>

    );
  }
  const { isLoaded } = useJsApiLoader({
    googleMapsApiKey: "AIzaSyAhkyqtF5czuz-KzzOv3Z8skkl2b_9koDk",

  });

  if (!isLoaded) return <div>Loading....!</div>

  return (
    <>
    <Head>
      <title>Test Case - User Add</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/pro.ico" />
    </Head>
    <div className="md:flex min-h-screen relative">
      <SideNavBar />
      <div className="md:flex w-full ">
    
          <div className='w-full h-full p-20'>
            <Map />

          </div>
          </div>
    </div>
  </>
  )
}

export default userAdd