import React from 'react'

import Head from "next/head";
import SideNavBar from './component/SideNavbar'
function Index() {
  return (
    < >
      <Head>
        <title>Test Case - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <div className="md:flex min-h-screen relative">
      <SideNavBar />
      <div className="w-full p-10">
      
      
       </div>
    </div>
    </>
  )
}

export default Index